

THEMES = {
    "Sci-Fi": {
        "bg": "
        "btn_bg": "
        "hover": "
        "clicked": "
        "text": "
        "player": "
        "ai": "
        "win": "
        "score": "
        "control_bg": "
        "control_fg": "
        "control_active": "
        "exit_bg": "
        "exit_fg": "
        "exit_active": "
        "title_bg": "
        "title_fg": "
        "title_btn_bg": "
        "title_btn_fg": "
    },
    "Retro": {
        "bg": "
        "btn_bg": "
        "hover": "
        "clicked": "
        "text": "
        "player": "
        "ai": "
        "win": "
        "score": "
        "control_bg": "
        "control_fg": "
        "control_active": "
        "exit_bg": "
        "exit_fg": "
        "exit_active": "
        "title_bg": "
        "title_fg": "
        "title_btn_bg": "
        "title_btn_fg": "
    },
    "Forest": {
        "bg": "
        "btn_bg": "
        "hover": "
        "clicked": "
        "text": "
        "player": "
        "ai": "
        "win": "
        "score": "
        "control_bg": "
        "control_fg": "
        "control_active": "
        "exit_bg": "
        "exit_fg": "
        "exit_active": "
        "title_bg": "
        "title_fg": "
        "title_btn_bg": "
        "title_btn_fg": "
    },
    "Dark Mode": {
        "bg": "
        "btn_bg": "
        "hover": "
        "clicked": "
        "text": "
        "player": "
        "ai": "
        "win": "
        "score": "
        "control_bg": "
        "control_fg": "
        "control_active": "
        "exit_bg": "
        "exit_fg": "
        "exit_active": "
        "title_bg": "
        "title_fg": "
        "title_btn_bg": "
        "title_btn_fg": "
    },
    "Ocean": {
        "bg": "
        "btn_bg": "
        "hover": "
        "clicked": "
        "text": "
        "player": "
        "ai": "
        "win": "
        "score": "
        "control_bg": "
        "control_fg": "
        "control_active": "
        "exit_bg": "
        "exit_fg": "
        "exit_active": "
        "title_bg": "
        "title_fg": "
        "title_btn_bg": "
        "title_btn_fg": "
    },
    "Sunset": {
        "bg": "
        "btn_bg": "
        "hover": "
        "clicked": "
        "text": "
        "player": "
        "ai": "
        "win": "
        "score": "
        "control_bg": "
        "control_fg": "
        "control_active": "
        "exit_bg": "
        "exit_fg": "
        "exit_active": "
        "title_bg": "
        "title_fg": "
        "title_btn_bg": "
        "title_btn_fg": "
    }
}

DEFAULT_THEME = "Sci-Fi"